baseURL = "https://stdin.top/"
languageCode = "en-us"
title = "<stdin>"

theme = "kavi-hugo-theme"
enableRobotsTXT = true
enableEmoji = true
paginate = 6 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.


pygmentscodefences = true
pygmentsUseClasses=true
pygmentscodefencesguesssyntax = true


[params]
description = "My writings about technology and other things. Herein I document my experiences on various topics."
DefaultContentLanguage = "en"
subtitle = "My Thoughts, Trials and Adventures"
utterances = "jkotra/stdin.top-comments"
favicon = "/static/chip.png"
#logo = "/static/chip.svg"
blinkingcursor = true
browserthemecolor="#2e2847"

math = true

googleAnalytics = "G-YW8V9DTR0N"

enableAds = true
googleAdsense = "ca-pub-8658473214995139"

[author]
name = "Jagadeesh Kotra"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
unsafe = true

[[params.social]]
name = "Mail"
icon = "far fa-envelope"
url = "mailto:jagadeesh@stdin.top"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/jkotra/"

[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/jagadeesh_kotra"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "index.xml"


# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

[[menu.main]]
	name = "Portfolio"
	identifier = "portfolio"
	url = "/portfolio/"
	weight = 3

[[menu.main]]
	name = "PGP"
	identifier = "pgp"
	url = "/pgp/"
	weight = 5

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
